### ISSUE TITLE
Is there a API lookup address list?

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/PluginTemplate#2]
like this：
StructList FindAdressList(duint StartAdress,duint Number) ；

StartAdress = 77534886
FindAdressList(0x77534886,10);

return:
77534889	0
7753488F	1
77534895	2
77534897	3
7753489A	4
7753489C	5
775348A0	6
775348A2	7
775348A4	8
775348A6	9

**Comment by mrexodia** [comment]
Could you elaborate? I don't quite understand what you mean from this small example...

**Comment by stonedreamforest** [comment]
![qq 20170311223053](https://cloud.githubusercontent.com/assets/16742566/23824050/7b84de82-06aa-11e7-8498-cce765850247.png)

**Comment by mrexodia** [comment]
Okay so with this picture I call `FindAddressList(0x77534895, 10)` what will it return? You want to disassemble 10 times and return the addresses of all instructions? Or search for a reference of 0x10?

**Comment by stonedreamforest** [comment]
return The address list starts with adress((0x77534895,) for a total of 10

if i can  get adress list 

i  can use  set breakpoint  or remove break point    Easier to achieve some features

**Comment by mrexodia** [comment]
Okay so you want this as a plugin api or as an expression function for use in scripts?

**Comment by stonedreamforest** [comment]
yes  need a plugin api

**Comment by mrexodia** [comment]
```c++
std::vector<duint> GetAddresses(duint start, duint count)
{
    std::vector<duint> result;
    std::vector<unsigned char> data(count * 16);
    if(DbgMemRead(start, data.data(), data.size()))
    {
        BASIC_INSTRUCTION_INFO info;
        for(duint i = 0; count; count--)
        {
            i += DbgFunctions()->DisasmFast(data.data() + i, start + i, &info) ? info.size : 1;
            result.push_back(start + i);
        }
    }
    return result;
}
```

**Comment by stonedreamforest** [comment]
Nice work :+1:
