### ISSUE TITLE
Better to add a way to import the PluginTemplate to VS2017

### ISSUE THREAD

**Issue by dbsxdbsx** [x64dbg/PluginTemplate#4]
I use VS2017, and I found it not accessible to get the installed template through tutorial---
```
copy *.zip to Documents\Visual Studio 2017\Templates\ProjectTemplates\Visual C++ Project\.
```
But I did succeed by exporting  the solution as template.  
So this is just an advice.

**Comment by BedolagaEvgen** [comment]
I do not think that the question is still relevant, but:
I came across this in VS2019. The problem is that these templates are not automatically displayed, they must be run through a text search,

**Comment by dbsxdbsx** [comment]
thanks for your answer.

**Comment by BedolagaEvgen** [comment]
Better late than never?

**Comment by dbsxdbsx** [comment]
@BedolagaEvgen ,Yeah~ The issue could be closed now, thanks.
