### ISSUE TITLE
Where to get plugin SDK?

### ISSUE THREAD

**Issue by Epenko1337** [x64dbg/PluginTemplate#8]
I'm unable to find plugin SDK. I See it in **Example plugins** repositories at wiki plugins section but there is no SDK in template repository. So where should i get it to have latest version?

**Comment by mrexodia** [comment]
The SDK is automatically downloaded by CMake. They are part of the snapshots.

**Comment by Epenko1337** [comment]
But why after downloading cmake wont copy it into src folder too?

**Comment by mrexodia** [comment]
It's just not really necessary? The snapshot.zip will be downloaded in the folder you specify with `cmake -B <folder>` and then it will be cached there. You can also quite easily adjust the cmake to use it from whatever folder.
